name: Server-side build and tests

on: [push]

env: 
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}            

jobs:
  build:
    runs-on: ubuntu-latest
    
    services: 
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
        
    defaults:
      run:
        working-directory: ./server
        
    steps:
    - uses: actions/checkout@v4
    - name: Build server and db, and run tests
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json

    - run: npm ci
    - run: npm run build --if-present
    - run: cat $(find ../db -name socialMediaDB.sql) | mysql --protocol=tcp -u "$DB_USER" -p"$DB_PASSWORD" -h localhost -P 3306
    - run: npm test
          
